spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flyway-migration
    username: postgres
    password: Jkushnazarov25121998
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true